# Generated by Django 2.2.7 on 2019-11-13 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('ticket_status', models.CharField(choices=[('N', 'New'), ('IP', 'In_progress'), ('D', 'Done'), ('IN', 'Invalid')], default='N', max_length=2)),
            ],
        ),
    ]
